# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('dash-migration-v2', ['dash-migration', 'internet', 'wifi', 'buildings', 'applications', 'point-to-point','internet-apps'])
    obj.source = 'dash-migration-v2.cc'
